
#build notes:
#  pio run 1> file.log 2>&1
#to save output
# 
#A1, A8, A9 are not defined in pins_arduion.h for some reason ()
[esp32_common]
platform = espressif32@2.1
#platform = espressif32@3.2.0 
#platform = espressif32
framework = arduino
board = esp32dev  #esp32-mks-dlc32
#board_build.f_cpu = 160000000L
#board_build.f_flash = 80000000L
board_build.flash_mode = dout

				
#build_src_filter = 
#	+<*.h> +<*.s> +<*.S> +<*.cpp> +<*.c> +<*.ino> +<src/> -<test/> -<tests/>
#	-<.git/> -<data/> 

build_flags = -mtext-section-literals
	-Wno-unused-variable
	-Wno-unused-function
	-w


lib_deps = 
	ESP Async WebServer
	ArduinoLog
	ArduinoJson
	AsyncMqttClient
	ESP32Servo
	ESP32 AnalogWrite
	FastLED

lib_ignore = Adafruit SPIFlash

#build_src_filter = 
#	+<*.h> +<*.s> +<*.S> +<*.cpp> +<*.c> +<*.ino> +<src/> -<test/> -<tests/>
#	-<.git/> -<data/> 

    ; For MKS DLC32
[env:mks_dlc32_v2_1]
extends = esp32_common

#huge_app.csv:
# Name	Type	SubType	Offset	Size	Flags
#nvs	data	nvs	0x9000	0x5000	
#otadata	data	ota	0xe000	0x2000	app0	app	ota_0	0x10000	0x300000	
#spiffs	data	spiffs	0x310000	0xE0000	
#coredump	data	coredump	0x3F0000	0x10000	

board_build.partitions = default_8MB.csv
upload_port = COM3
upload_speed = 921600
monitor_port = COM3
monitor_speed = 115200
build_flags = ${esp32_common.build_flags}
	-D ENABLE_I2S
	-D ENABLE_DISPLAY
	-D SERIAL_DISPLAY
	-D LED_WS2812B_PIN=32
	-D I2S_WS=17
	-D I2S_BCK=16
	-D I2S_DATA=21
	-D RXD2=19
	-D TXD2=4
	-D BEEPER=135
	

lib_deps =
  ${esp32_common.lib_deps}
 ; https://github.com/rzeldent/esp32-smartdisplay.git



